# Generated by Django 3.2.5 on 2021-07-31 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('student', models.ManyToManyField(related_name='lesson_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ManyToManyField(related_name='lesson_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='textbooks',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Textbooks',
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.ManyToManyField(default='', related_name='lesson_title', to='students.Textbook'),
        ),
    ]
