# Generated by Django 3.2.5 on 2021-07-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210731_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='page',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='page',
        ),
        migrations.AddField(
            model_name='lesson',
            name='page',
            field=models.ManyToManyField(default='', related_name='lesson_page', to='students.Textbook'),
        ),
    ]
