# Generated by Django 3.2.5 on 2021-07-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210801_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbook',
            options={},
        ),
        migrations.AddField(
            model_name='textbook',
            name='course',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='textbook', to='students.course'),
            preserve_default=False,
        ),
    ]
