# Generated by Django 3.2.5 on 2021-08-01 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20210801_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(related_name='lesson', to='students.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='score'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.user'),
            preserve_default=False,
        ),
    ]
