# Generated by Django 3.2.5 on 2021-08-02 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210801_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='textbook',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson', to='students.course'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='page',
        ),
        migrations.AddField(
            model_name='lesson',
            name='page',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Textbook',
        ),
    ]
