# Generated by Django 3.2.5 on 2021-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_lesson_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
