# Generated by Django 3.2.5 on 2021-08-09 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20210807_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_word', models.CharField(max_length=20)),
                ('meaning', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
